title: TI no Canadá
url: https://ti-no-canada.github.io/imigracao-para-o-canada
repository: https://github.com/ti-no-canada/imigracao-para-o-canada
description: >
  O objetivo deste site é auxiliar brasileiros e falantes de português com informações úteis sobre o Canadá. Explore os conteúdos, pesquise constantemente e participe do nosso grupo no Telegram para tirar dúvidas e compartilhar experiências.

# SEO settings
tagline: Guia completo sobre imigração e vida no Canadá para profissionais de TI
lang: pt-BR
author: TI no Canadá
keywords: >
  brasileiros no canada, imigrar para o canada, morar no canada, 
  trabalhar no canada, visto canadense, express entry, 
  profissionais de TI no canada, tecnologia canada,
  comunidade brasileira canada, imigracao canada, 
  emprego ti canada, salarios ti canada, custo de vida canada,
  processo imigratorio canada, estudar no canada, 
  programador no canada, desenvolvedor canada

# Open Graph / Social Media
og_image: /assets/images/og-image.png

# Analytics
google_analytics: UA-XXXXXXXX-X
google_site_verification: google-site-verification-code

# Sitemap settings
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

social:
  name: TI no Canadá
  links:
    - https://t.me/tinocanada
    - https://github.com/ti-no-canada
    - https://www.linkedin.com/company/ti-no-canada
    - https://www.facebook.com/tinocanada
    - https://twitter.com/tinocanada

theme: just-the-docs
nav_enabled: true
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-mentions
  - jemoji

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
      image: /assets/images/og-image.png
      author: TI no Canadá

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/
  - docs/assets
  - docs/.github
  - docs/_sass
  - docs/_config.yml

aux_links:
  Telegram: https://t.me/tinocanada
